name: Update SonyLIV HDNEA Token

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp requests

      - name: Create cookies.txt from secret
        env:
          COOKIES_CONTENT: ${{ secrets.COOKIES_CONTENT }}
        run: |
          echo "$COOKIES_CONTENT" > cookies.txt

      - name: Run HDNEA update script
        run: |
          python sonyliv_json_hdnea_updater.py "https://apiv4.sonyliv.com/AGL/4.7/R/ENG/MWEB/IN/BR/CONTENT/VIDEOURL/VOD/1090492435/freepreview" "Slivcdn.json" --cookies cookies.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Slivcdn.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Slivcdn.json with new HDNEA token"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        if: always
        run: |
          rm -f cookies.txt
